# Default values for senzing-mock-data-generator.

replicaCount: 1

image:
  repository: data.dockter.com:5000/senzing/mock-data-generator
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

senzing:
  subcommand: "url-to-kafka"
  kafkaBootstrapServerHost: "my-kafka-kafka"
  kafkaBootstrapServerPort: "9092"
  kafkaTopic: "senzing-kafka-topic"
  inputUrl: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
  recordMax: "10000"
  recordMonitor: "1000"
  