affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  repository: senzing/mock-data-generator
  tag: latest

ingress:
  annotations: {}
  enabled: false
  hosts:
    - chart-example.local
  paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  inputUrl: "https://s3.amazonaws.com/public-read-access/TestDataSets/loadtest-dataset-1M.json"
  kafkaBootstrapServerHost: "my-kafka-kafka"
  kafkaBootstrapServerPort: "9092"
  kafkaTopic: "senzing-kafka-topic"
  recordMax: "10000"
  recordMonitor: "1000"
  subcommand: "url-to-kafka"

service:
  port: 80
  type: ClusterIP

tolerations: []
