affinity: {}
fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: senzing/resolver
  tag: latest
imagePullSecrets: []
ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
  paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  debug: 0

service:
  port: 80
  type: ClusterIP

tolerations: []
