affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/resolver
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
  paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  optSenzingClaim: opt-senzing-claim
  subcommand: service

service:
  port: 80
  type: ClusterIP

tolerations: []
