affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/resolver
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
  paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  optSenzingClaim: senzing-persistent-volume-claim
  subcommand: service

service:
  port: 5000
  targetPort: http
  type: ClusterIP

tolerations: []
