affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: coleifer/sqlite-web
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  database: G2C.db
  persistentVolumeClaim: senzing-persistent-volume-claim

service:
  port: 80
  type: ClusterIP

tolerations: []
