replicaCount: 1

image:
  repository: senzing/mysql-init
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

mysql:
  username: "g2"
  password: "g2"
  host: ""
  database: "G2"
  file: "g2/data/g2core-schema-mysql-create.sql"
  storageClaim: "opt-senzing-claim"