affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
# repository: arey/mysql-client
  repository: senzing/mysql-init
  tag: latest

mysql:
  database: G2
  file: senzing-g2/resources/schema/g2core-schema-mysql-create.sql
  host: ""
  password: g2
  persistentVolumeClaim: senzing-persistent-volume-claim
  username: g2

nameOverride: ""
nodeSelector: {}
resources: {}

tolerations: []
