affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: arey/mysql-client
  tag: latest

mysql:
  database: "G2"
  file: "g2/data/g2core-schema-mysql-create.sql"
  host: ""
  password: "g2"
  persistentVolumeClaim: "senzing-persistent-volume-claim"
  username: "g2"

nameOverride: ""
nodeSelector: {}
resources: {}

tolerations: []
