fullnameOverride: ""

image:
  pullPolicy: IfNotPresent
  repository: senzing/mysql-init
  tag: latest

nameOverride: ""

mysql:
  database: "G2"
  file: "g2/data/g2core-schema-mysql-create.sql"
  host: ""
  password: "g2"
  storageClaim: "opt-senzing-claim"
  username: "g2"

replicaCount: 1
