affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: store/senzing/senzing-package
  tag: 1.10.19198

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  optSenzingClaim: "opt-senzing-claim"
  subcommand: "install"

service:
  port: 80
  type: ClusterIP

tolerations: []
