image:
  repository: senzing/senzing-package
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
    - chart-example.local
  tls: []

senzing:
  subcommand: "install"
  optSenzingClaim: "opt-senzing-claim"
