affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/yum
  tag: latest

imagePullSecrets: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  acceptEula: I_ACCEPT_THE_SENZING_EULA
  optSenzingClaim: opt-senzing-claim
  yumParameters: ["-y", "localinstall", "/rpms/senzingapi-1.11.0-19221.x86_64.rpm"]

tolerations: []
