affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/yum
  tag: latest

imagePullSecrets: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  acceptEula: ""
  optSenzingClaim: senzing-persistent-volume-claim

tolerations: []
