db2:
  password: "db2inst1"
  optSenzingStorageClaim: "opt-senzing-claim"

fullnameOverride: ""

global:
  image:
    secretName: ""

image:
  repository: ibmcom/db2express-c
  tag: latest
  pullPolicy: IfNotPresent

ingress:
  enabled: false

nameOverride: ""
replicaCount: 1

service:
  type: ClusterIP
  port: 80
