db2:
  optSenzingStorageClaim: "opt-senzing-claim"
  password: "db2inst1"

fullnameOverride: ""

global:
  image:
    secretName: ""

image:
  pullPolicy: IfNotPresent
  repository: ibmcom/db2express-c
  tag: 10.5.0.5-3.10.0

ingress:
  enabled: false

nameOverride: ""
replicaCount: 1

service:
  port: 80
  type: ClusterIP
