apiVersion: v1
appVersion: "1.0"
description: A cluster of 3 DB2 databases
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
 - kafka
name: senzing-db2-cluster
version: 0.1.0
