apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-api-server.fullname" . }}
  labels:
{{ include "senzing-api-server.labels" . | indent 4 }}
  {{- with .Values.deployment.metadata.annotations }}
  annotations:
  {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-api-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-api-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- with .Values.deployment.spec.template.metadata.annotations }}
      annotations:
      {{ toYaml . | indent 8 }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          args:
            - "-httpPort"
            - "8080"
            {{- if .Values.senzing.allowedOrigins }}
            - "-allowedOrigins"
            - {{ .Values.senzing.allowedOrigins | quote }}
            {{- end }}
            {{- if .Values.senzing.bindAddr }}
            - "-bindAddr"
            - {{ .Values.senzing.bindAddr | quote }}
            {{- end }}
            {{- if .Values.senzing.concurrency }}
            - "-concurrency"
            - {{ .Values.senzing.concurrency | quote }}
            {{- end }}
            {{- if .Values.senzing.iniFile }}
            - "-iniFile"
            - {{ .Values.senzing.iniFile | quote }}
            {{- end }}
            {{- if .Values.senzing.moduleName }}
            - "-moduleName"
            - {{ .Values.senzing.moduleName | quote }}
            {{- end }}
            {{- if .Values.senzing.monitorFile }}
            - "-monitorFile"
            - {{ .Values.senzing.monitorFile | quote }}
            {{- end }}
            {{- if .Values.senzing.verbose }}
            - "-verbose"
            {{- end }}
            {{- if .Values.senzing.engineConfigurationJson }}
            - "-initEnvVar"
            - "SENZING_ENGINE_CONFIGURATION_JSON"
            {{- end }}
          env:
            {{- if .Values.senzing.engineConfigurationJson }}
            - name: SENZING_ENGINE_CONFIGURATION_JSON
              value: >-
              {{ .Values.senzing.engineConfigurationJson  | nindent 16 }}
            {{- end }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data/1.0.0
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
            - name: senzing-storage
              mountPath: /opt/IBM
              subPath: senzing-db2-drivers
          {{- end }}
          workingDir: /app
      {{- if .Values.rbacEnabled}}
      serviceAccountName: {{ template "senzing-api-server.fullname" . }}
      {{- end }}
      {{- if .Values.senzing.persistentVolumeClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
