apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-api-server.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "senzing-api-server.name" . }}
    helm.sh/chart: {{ include "senzing-api-server.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-api-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-api-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:

      {{ if .Values.senzing.optSenzingClaim }}
      volumes:
        - name: opt-senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.optSenzingClaim }}
      {{ end }}

      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: SENZING_DATABASE_URL
              value: "{{ .Values.senzing.databaseUrl }}"

            {{ if .Values.senzing.debug }}
            - name: SENZING_DEBUG
              value: "{{ .Values.senzing.debug }}"
            {{ end }}

          command:
            - /app/docker-entrypoint.sh
            - java -jar /app/senzing-api-server.jar    
          args:
            - "-httpPort 80"

            {{ if .Values.senzing.allowedOrigins }}
            - "-allowedOrigins {{ .Values.senzing.allowedOrigins }}"
            {{ end }}

            {{ if .Values.senzing.bindAddr }}
            - "-bindAddr {{ .Values.senzing.bindAddr }}"
            {{ end }}

            {{ if .Values.senzing.concurrency }}
            - "-concurrency {{ .Values.senzing.concurrency }}"
            {{ end }}

            {{ if .Values.senzing.iniFile }}
            - "-iniFile {{ .Values.senzing.iniFile }}"
            {{ end }}

            {{ if .Values.senzing.moduleName }}
            - "-moduleName {{ .Values.senzing.moduleName }}"
            {{ end }}

            {{ if .Values.senzing.monitorFile }}
            - "-monitorFile {{ .Values.senzing.monitorFile }}"
            {{ end }}

            {{ if .Values.senzing.verbose }}
            - "-verbose
            {{ end }}


          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

          {{ if .Values.senzing.optSenzingClaim }}
          volumeMounts:
            - name: opt-senzing-storage
              mountPath: /opt/senzing
          {{ end }}

          workingDir: /app

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
