apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-stream-loader.fullname" . }}
  labels:
{{ include "senzing-stream-loader.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-stream-loader.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-stream-loader.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.senzing.dataSource }}
            - name: SENZING_DATA_SOURCE
              value: "{{ .Values.senzing.dataSource }}"
            {{- end }}
            {{- if .Values.senzing.databaseUrl }}
            - name: SENZING_DATABASE_URL
              value: "{{ .Values.senzing.databaseUrl }}"
            {{- end }}
            {{- if .Values.senzing.debug }}
            - name: SENZING_DEBUG
              value: "{{ .Values.senzing.debug }}"
            {{- end }}
            {{- if .Values.senzing.entityType }}
            - name: SENZING_ENTITY_TYPE
              value: "{{ .Values.senzing.entityType }}"
            {{- end }}
            {{- if .Values.senzing.entrypointSleep }}
            - name: SENZING_ENTRYPOINT_SLEEP
              value: "{{ .Values.senzing.entrypointSleep }}"
            {{- end }}
            {{- if .Values.senzing.kafkaBootstrapServerHost }}
            - name: SENZING_KAFKA_BOOTSTRAP_SERVER
              value: "{{ .Values.senzing.kafkaBootstrapServerHost }}:{{ .Values.senzing.kafkaBootstrapServerPort }}"
            {{- end }}
            {{- if .Values.senzing.kafkaGroup }}
            - name: SENZING_KAFKA_GROUP
              value: "{{ .Values.senzing.kafkaGroup }}"
            {{- end }}
            {{- if .Values.senzing.kafkaTopic }}
            - name: SENZING_KAFKA_TOPIC
              value: "{{ .Values.senzing.kafkaTopic }}"
            {{- end }}
            {{- if .Values.senzing.logLevel }}
            - name: SENZING_LOG_LEVEL
              value: "{{ .Values.senzing.logLevel }}"
            {{- end }}
            {{- if .Values.senzing.monitoringPeriodInSeconds }}
            - name: SENZING_MONITORING_PERIOD_IN_SECONDS
              value: "{{ .Values.senzing.monitoringPeriodInSeconds }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqHost }}
            - name: "SENZING_RABBITMQ_HOST"
              value: "{{ .Values.senzing.rabbitmqHost }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqPassword }}
            - name: "SENZING_RABBITMQ_PASSWORD"
              value: "{{ .Values.senzing.rabbitmqPassword }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqQueue }}
            - name: "SENZING_RABBITMQ_QUEUE"
              value: "{{ .Values.senzing.rabbitmqQueue }}"
            {{- end }}
            {{- if .Values.senzing.rabbitmqUsername }}
            - name: "SENZING_RABBITMQ_USERNAME"
              value: "{{ .Values.senzing.rabbitmqUsername }}"
            {{- end }}
            {{- if .Values.senzing.threadsPerProcess }}
            - name: SENZING_THREADS_PER_PROCESS
              value: "{{ .Values.senzing.threadsPerProcess }}"
            {{- end }}
            {{- if .Values.senzing.subcommand }}
            - name: SENZING_SUBCOMMAND
              value: "{{ .Values.senzing.subcommand }}"
            {{- end }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.senzing.persistentVolumeClaim }}
          volumeMounts:
            - name: senzing-storage
              mountPath: /opt/senzing/data
              subPath: senzing-data/1.0.0
            - name: senzing-storage
              mountPath: /etc/opt/senzing
              subPath: senzing-etc
            - name: senzing-storage
              mountPath: /opt/senzing/g2
              subPath: senzing-g2
            - name: senzing-storage
              mountPath: /var/opt/senzing
              subPath: senzing-var
            - name: senzing-storage
              mountPath: /opt/IBM
              subPath: senzing-db2-drivers
          {{- end }}
      {{- if .Values.senzing.persistentVolumeClaim }}
      volumes:
        - name: senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.persistentVolumeClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
