apiVersion: v1
kind: Service
metadata:
  name: {{ include "ibm-db2express-c.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "ibm-db2express-c.name" . }}
    helm.sh/chart: {{ include "ibm-db2express-c.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }} 
      targetPort: 50000
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    app.kubernetes.io/name: {{ include "ibm-db2express-c.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
