affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/senzing-debug
  tag: latest

ingress:
  annotations: {}
  enabled: false
  hosts:
    - chart-example.local
  paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  databaseUrl: ""
  debug: 0
  persistentVolumeClaim: "senzing-persistent-volume-claim"

service:
  port: 80
  type: ClusterIP

tolerations: []
