replicaCount: 1

image:
  repository: senzing/stream-loader
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
    - chart-example.local
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

senzing:
  subcommand: "kafka"
  optSenzingClaim: "opt-senzing-claim"
