apiVersion: v1
appVersion: "1.0"
description: A docker wrapper over G2ConfigTool.py
home: http://senzing.com
icon: https://avatars2.githubusercontent.com/u/43552726?s=200&v=4
keywords:
 - senzing
name: senzing-g2configtool
sources:
 - https://github.com/Senzing/senzing-package
version: 0.2.0

