apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "senzing-package.fullname" . }}
spec:
  template:
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.senzing.debug }}
            - name: "SENZING_DEBUG"
              value: "{{ .Values.senzing.debug }}"
            {{- end }}
            {{- if .Values.senzing.senzingDir }}
            - name: "SENZING_DIR"
              value: "{{ .Values.senzing.senzingDir }}"
            {{- end }}
            {{- if .Values.senzing.senzingPackage }}
            - name: "SENZING_PACKAGE"
              value: "{{ .Values.senzing.senzingPackage }}"
            {{- end }}
            {{- if .Values.senzing.subcommand }}
            - name: "SENZING_SLEEP_TIME"
              value: "{{ .Values.senzing.sleepTime }}"
            {{- end }}
            {{- if .Values.senzing.subcommand }}
            - name: "SENZING_SUBCOMMAND"
              value: "{{ .Values.senzing.subcommand }}"
            {{- end }}
          image: {{ template "senzing.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.senzing.optSenzingClaim }}
          volumeMounts:
            - name: opt-senzing-storage
              mountPath: /opt/senzing
          {{- end }}
      restartPolicy: Never
      {{- if .Values.senzing.optSenzingClaim }}
      volumes:
        - name: opt-senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.optSenzingClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
