affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  repository: senzing/stream-configuration
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
  paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  optSenzingClaim: "opt-senzing-claim"
  subcommand: "kafka"

service:
  type: ClusterIP
  port: 80

tolerations: []
