apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "db2-client.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "db2-client.name" . }}
    helm.sh/chart: {{ include "db2-client.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "db2-client.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "db2-client.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          env:
            - name: "DB2INST1_PASSWORD"
              value: "{{ .Values.db2.password }}"
            - name: "LICENSE"
              value: "accept"
                        
          command: ["/bin/bash", "sleep 1d"]
