image:
  pullPolicy: Always
  registry: docker.io
  repository: dockage/phppgadmin
  tag: latest

ingress:
  annotations:
  enabled: false
  tls:

phppgadmin:
  ajaxRefresh: 3
  autoComplete: default on
  defaultLang: auto
  extraLoginSecurity: false
  helpBase: http://www.postgresql.org/docs/%s/interactive/
  leftWidth: 200
  maxChars: 50
  maxRows: 30
  minPasswordLength: 1
  ownedOnly: false
  serverDefaultDb: template1
  serverDesc: PostgreSQL
  serverHost:
  serverPgDumpAllPath: /usr/bin/pg_dumpall
  serverPgDumpPath: /usr/bin/pg_dump
  serverPort: 5432
  serverSslMode: allow
  showAdvanced: false
  showComments: true
  showOids: false
  showSystem: false
  theme: default
  userXhtlmStrict: false

replicaCount: 1
resources: {}

service:
  externalPort: 8080
  internalPort: 80
  name: phppgadmin
  type: LoadBalancer
