affinity: {}
fullnameOverride: ""

db2:
  persistentVolumeClaim: db2-database-claim

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/db2-driver-installer
  tag: latest

imagePullSecrets: []

ingress:
  annotations: {}
  enabled: false
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  persistentVolumeClaim: senzing-persistent-volume-claim

service:
  port: 80
  type: ClusterIP

tolerations: []
