affinity: {}
fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: senzing/senzing-api-server
  tag: latest

ingress:
  annotations: {}
  enabled: false
  hosts:
    - chart-example.local
  paths: []
  tls: []

nameOverride: ""
nodeSelector: {}
replicaCount: 1
resources: {}

senzing:
  bindAddr: all
  iniFile: /etc/opt/senzing/G2Module.ini
  optSenzingClaim: senzing-persistent-volume-claim

service:
  port: 8080
  type: ClusterIP

tolerations: []
