# Default values for senzing-api-server.

replicaCount: 1

image:
  repository: senzing/senzing-api-server
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  paths: []
  hosts:
    - chart-example.local
  tls: []

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

senzing:
  bindAddr: all
  iniFile: "/opt/senzing/g2/python/G2Module.ini"
  optSenzingClaim: "opt-senzing-claim"
