fullnameOverride: ""

image:
  pullPolicy: Always
  registry: docker.io
  repository: jbergknoff/postgresql-client
  tag: latest

nameOverride: ""

postgresql:
  host: ""
  password: postgres
  username: postgres

replicaCount: 1
