apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "senzing-debug.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "senzing-debug.name" . }}
    helm.sh/chart: {{ include "senzing-debug.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "senzing-debug.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "senzing-debug.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          env:
            {{- if .Values.senzing.databaseUrl }}
            - name: SENZING_DATABASE_URL
              value: "{{ .Values.senzing.databaseUrl }}"
            {{- end }}
            {{- if .Values.senzing.debug }}
            - name: SENZING_DEBUG
              value: "{{ .Values.senzing.debug }}"
            {{- end }}
            {{- if .Values.senzing.entrypointSleep }}
            - name: SENZING_ENTRYPOINT_SLEEP
              value: "{{ .Values.senzing.entrypointSleep }}"
            {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.senzing.optSenzingClaim }}
          volumeMounts:
            - name: opt-senzing-storage
              mountPath: /opt/senzing
          {{- end }}
      {{- if .Values.senzing.optSenzingClaim }}
      volumes:
        - name: opt-senzing-storage
          persistentVolumeClaim:
            claimName: {{ .Values.senzing.optSenzingClaim }}
      {{- end }}
# --- Standard suffix ---
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
