# Default values for senzing-hello-world-on-hub-docker-com.

replicaCount: 1

image:
  repository: senzing/hello-world-on-hub-docker-com
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

senzing:
  sleepTime: 300